name: Deploy Next.js App to GitHub Pages

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
      
      - name: Install TailwindCSS and related packages
        run: |
          npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
          npm install -D @tailwindcss/forms @tailwindcss/typography
          
      - name: Install sharp for image optimization
        run: |
          npm install sharp --force
          
      - name: Verify TailwindCSS installation
        run: |
          npx tailwindcss --help
          ls -la node_modules/tailwindcss
          cat package.json
          
      - name: Create necessary config files if missing
        run: |
          if [ ! -f "postcss.config.js" ]; then
            echo "Creating postcss.config.js"
            echo "module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }" > postcss.config.js
          fi
          
          if [ ! -f "tailwind.config.js" ]; then
            echo "Creating tailwind.config.js"
            npx tailwindcss init
          fi
        
      - name: Build Next.js app
        run: |
          npm run build
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 